#!/usr/bin/python

# This generates code for ini reading.
# Run go generate in project folder.

import sys

def createFileContent():
    arrFields = []
    f = open("config.go", "r")
    reader = False
    for pos, line in enumerate(f):
        if reader == True and "}" in line:
            #reader = False
            break
        if reader:
            x = line.replace("string", "").strip()
            arrFields.append(x)
        if "type Config struct {" in line:
            reader = True

    cont = """package main

// Code generated by go generate; DO NOT EDIT.
// This file was generated with Python robot.

func makeStringToWriteToINI(cfg *Config) string {
\ts := ""
"""

    for sf in arrFields:
        cont += f'\ts += "{sf} = " + cfg.{sf} + "\\n"\n'

    cont += """
\treturn s
}
"""
    cont +="""
func readMapToCfgStruct(m map[string]string, cfg *Config) {
"""

    for sf in arrFields:
        cont += f'\tif _, ok := m["{sf}"]; ok ' + '{\n'
        cont += f'\t\tcfg.{sf} = m["{sf}"]\n' + '\t}\n'

    cont += "\n}\n"
    return cont



def genFile(fname, cont):
    f = open(fname, "w") #overwrites
    f.write(cont)
    f.close()



genFile("config-gen.go", createFileContent())
print("config-gen.go generated")
